/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: msg.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "msg.pb-c.h"
void   rpc__request__init
                     (Rpc__Request         *message)
{
  static const Rpc__Request init_value = RPC__REQUEST__INIT;
  *message = init_value;
}
size_t rpc__request__get_packed_size
                     (const Rpc__Request *message)
{
  assert(message->base.descriptor == &rpc__request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__request__pack
                     (const Rpc__Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__request__pack_to_buffer
                     (const Rpc__Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__Request *
       rpc__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__Request *)
     protobuf_c_message_unpack (&rpc__request__descriptor,
                                allocator, len, data);
}
void   rpc__request__free_unpacked
                     (Rpc__Request *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__msg__init
                     (Rpc__Msg         *message)
{
  static const Rpc__Msg init_value = RPC__MSG__INIT;
  *message = init_value;
}
size_t rpc__msg__get_packed_size
                     (const Rpc__Msg *message)
{
  assert(message->base.descriptor == &rpc__msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__msg__pack
                     (const Rpc__Msg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__msg__pack_to_buffer
                     (const Rpc__Msg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__Msg *
       rpc__msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__Msg *)
     protobuf_c_message_unpack (&rpc__msg__descriptor,
                                allocator, len, data);
}
void   rpc__msg__free_unpacked
                     (Rpc__Msg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__number_msg__init
                     (Rpc__NumberMsg         *message)
{
  static const Rpc__NumberMsg init_value = RPC__NUMBER_MSG__INIT;
  *message = init_value;
}
size_t rpc__number_msg__get_packed_size
                     (const Rpc__NumberMsg *message)
{
  assert(message->base.descriptor == &rpc__number_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__number_msg__pack
                     (const Rpc__NumberMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__number_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__number_msg__pack_to_buffer
                     (const Rpc__NumberMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__number_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__NumberMsg *
       rpc__number_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__NumberMsg *)
     protobuf_c_message_unpack (&rpc__number_msg__descriptor,
                                allocator, len, data);
}
void   rpc__number_msg__free_unpacked
                     (Rpc__NumberMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__number_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__bytes_msg__init
                     (Rpc__BytesMsg         *message)
{
  static const Rpc__BytesMsg init_value = RPC__BYTES_MSG__INIT;
  *message = init_value;
}
size_t rpc__bytes_msg__get_packed_size
                     (const Rpc__BytesMsg *message)
{
  assert(message->base.descriptor == &rpc__bytes_msg__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__bytes_msg__pack
                     (const Rpc__BytesMsg *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__bytes_msg__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__bytes_msg__pack_to_buffer
                     (const Rpc__BytesMsg *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__bytes_msg__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__BytesMsg *
       rpc__bytes_msg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__BytesMsg *)
     protobuf_c_message_unpack (&rpc__bytes_msg__descriptor,
                                allocator, len, data);
}
void   rpc__bytes_msg__free_unpacked
                     (Rpc__BytesMsg *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__bytes_msg__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__ping__init
                     (Rpc__Ping         *message)
{
  static const Rpc__Ping init_value = RPC__PING__INIT;
  *message = init_value;
}
size_t rpc__ping__get_packed_size
                     (const Rpc__Ping *message)
{
  assert(message->base.descriptor == &rpc__ping__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__ping__pack
                     (const Rpc__Ping *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__ping__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__ping__pack_to_buffer
                     (const Rpc__Ping *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__ping__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__Ping *
       rpc__ping__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__Ping *)
     protobuf_c_message_unpack (&rpc__ping__descriptor,
                                allocator, len, data);
}
void   rpc__ping__free_unpacked
                     (Rpc__Ping *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__ping__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__login__init
                     (Rpc__Login         *message)
{
  static const Rpc__Login init_value = RPC__LOGIN__INIT;
  *message = init_value;
}
size_t rpc__login__get_packed_size
                     (const Rpc__Login *message)
{
  assert(message->base.descriptor == &rpc__login__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__login__pack
                     (const Rpc__Login *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__login__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__login__pack_to_buffer
                     (const Rpc__Login *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__login__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__Login *
       rpc__login__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__Login *)
     protobuf_c_message_unpack (&rpc__login__descriptor,
                                allocator, len, data);
}
void   rpc__login__free_unpacked
                     (Rpc__Login *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__login__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__third_party_authority__init
                     (Rpc__ThirdPartyAuthority         *message)
{
  static const Rpc__ThirdPartyAuthority init_value = RPC__THIRD_PARTY_AUTHORITY__INIT;
  *message = init_value;
}
size_t rpc__third_party_authority__get_packed_size
                     (const Rpc__ThirdPartyAuthority *message)
{
  assert(message->base.descriptor == &rpc__third_party_authority__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__third_party_authority__pack
                     (const Rpc__ThirdPartyAuthority *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__third_party_authority__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__third_party_authority__pack_to_buffer
                     (const Rpc__ThirdPartyAuthority *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__third_party_authority__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__ThirdPartyAuthority *
       rpc__third_party_authority__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__ThirdPartyAuthority *)
     protobuf_c_message_unpack (&rpc__third_party_authority__descriptor,
                                allocator, len, data);
}
void   rpc__third_party_authority__free_unpacked
                     (Rpc__ThirdPartyAuthority *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__third_party_authority__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__broadcast_message__init
                     (Rpc__BroadcastMessage         *message)
{
  static const Rpc__BroadcastMessage init_value = RPC__BROADCAST_MESSAGE__INIT;
  *message = init_value;
}
size_t rpc__broadcast_message__get_packed_size
                     (const Rpc__BroadcastMessage *message)
{
  assert(message->base.descriptor == &rpc__broadcast_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__broadcast_message__pack
                     (const Rpc__BroadcastMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__broadcast_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__broadcast_message__pack_to_buffer
                     (const Rpc__BroadcastMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__broadcast_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__BroadcastMessage *
       rpc__broadcast_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__BroadcastMessage *)
     protobuf_c_message_unpack (&rpc__broadcast_message__descriptor,
                                allocator, len, data);
}
void   rpc__broadcast_message__free_unpacked
                     (Rpc__BroadcastMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__broadcast_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__deliver_message__init
                     (Rpc__DeliverMessage         *message)
{
  static const Rpc__DeliverMessage init_value = RPC__DELIVER_MESSAGE__INIT;
  *message = init_value;
}
size_t rpc__deliver_message__get_packed_size
                     (const Rpc__DeliverMessage *message)
{
  assert(message->base.descriptor == &rpc__deliver_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__deliver_message__pack
                     (const Rpc__DeliverMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__deliver_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__deliver_message__pack_to_buffer
                     (const Rpc__DeliverMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__deliver_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__DeliverMessage *
       rpc__deliver_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__DeliverMessage *)
     protobuf_c_message_unpack (&rpc__deliver_message__descriptor,
                                allocator, len, data);
}
void   rpc__deliver_message__free_unpacked
                     (Rpc__DeliverMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__deliver_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__server_info__init
                     (Rpc__ServerInfo         *message)
{
  static const Rpc__ServerInfo init_value = RPC__SERVER_INFO__INIT;
  *message = init_value;
}
size_t rpc__server_info__get_packed_size
                     (const Rpc__ServerInfo *message)
{
  assert(message->base.descriptor == &rpc__server_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__server_info__pack
                     (const Rpc__ServerInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__server_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__server_info__pack_to_buffer
                     (const Rpc__ServerInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__server_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__ServerInfo *
       rpc__server_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__ServerInfo *)
     protobuf_c_message_unpack (&rpc__server_info__descriptor,
                                allocator, len, data);
}
void   rpc__server_info__free_unpacked
                     (Rpc__ServerInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__server_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__player__init
                     (Rpc__Player         *message)
{
  static const Rpc__Player init_value = RPC__PLAYER__INIT;
  *message = init_value;
}
size_t rpc__player__get_packed_size
                     (const Rpc__Player *message)
{
  assert(message->base.descriptor == &rpc__player__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__player__pack
                     (const Rpc__Player *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__player__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__player__pack_to_buffer
                     (const Rpc__Player *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__player__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__Player *
       rpc__player__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__Player *)
     protobuf_c_message_unpack (&rpc__player__descriptor,
                                allocator, len, data);
}
void   rpc__player__free_unpacked
                     (Rpc__Player *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__player__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__login_result__init
                     (Rpc__LoginResult         *message)
{
  static const Rpc__LoginResult init_value = RPC__LOGIN_RESULT__INIT;
  *message = init_value;
}
size_t rpc__login_result__get_packed_size
                     (const Rpc__LoginResult *message)
{
  assert(message->base.descriptor == &rpc__login_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__login_result__pack
                     (const Rpc__LoginResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__login_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__login_result__pack_to_buffer
                     (const Rpc__LoginResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__login_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__LoginResult *
       rpc__login_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__LoginResult *)
     protobuf_c_message_unpack (&rpc__login_result__descriptor,
                                allocator, len, data);
}
void   rpc__login_result__free_unpacked
                     (Rpc__LoginResult *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__login_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__error_code__init
                     (Rpc__ErrorCode         *message)
{
  static const Rpc__ErrorCode init_value = RPC__ERROR_CODE__INIT;
  *message = init_value;
}
size_t rpc__error_code__get_packed_size
                     (const Rpc__ErrorCode *message)
{
  assert(message->base.descriptor == &rpc__error_code__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__error_code__pack
                     (const Rpc__ErrorCode *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__error_code__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__error_code__pack_to_buffer
                     (const Rpc__ErrorCode *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__error_code__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__ErrorCode *
       rpc__error_code__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__ErrorCode *)
     protobuf_c_message_unpack (&rpc__error_code__descriptor,
                                allocator, len, data);
}
void   rpc__error_code__free_unpacked
                     (Rpc__ErrorCode *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__error_code__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__key_value__init
                     (Rpc__KeyValue         *message)
{
  static const Rpc__KeyValue init_value = RPC__KEY_VALUE__INIT;
  *message = init_value;
}
size_t rpc__key_value__get_packed_size
                     (const Rpc__KeyValue *message)
{
  assert(message->base.descriptor == &rpc__key_value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__key_value__pack
                     (const Rpc__KeyValue *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__key_value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__key_value__pack_to_buffer
                     (const Rpc__KeyValue *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__key_value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__KeyValue *
       rpc__key_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__KeyValue *)
     protobuf_c_message_unpack (&rpc__key_value__descriptor,
                                allocator, len, data);
}
void   rpc__key_value__free_unpacked
                     (Rpc__KeyValue *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__key_value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__configs__init
                     (Rpc__Configs         *message)
{
  static const Rpc__Configs init_value = RPC__CONFIGS__INIT;
  *message = init_value;
}
size_t rpc__configs__get_packed_size
                     (const Rpc__Configs *message)
{
  assert(message->base.descriptor == &rpc__configs__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__configs__pack
                     (const Rpc__Configs *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__configs__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__configs__pack_to_buffer
                     (const Rpc__Configs *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__configs__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__Configs *
       rpc__configs__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__Configs *)
     protobuf_c_message_unpack (&rpc__configs__descriptor,
                                allocator, len, data);
}
void   rpc__configs__free_unpacked
                     (Rpc__Configs *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__configs__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__assistant_config__init
                     (Rpc__AssistantConfig         *message)
{
  static const Rpc__AssistantConfig init_value = RPC__ASSISTANT_CONFIG__INIT;
  *message = init_value;
}
size_t rpc__assistant_config__get_packed_size
                     (const Rpc__AssistantConfig *message)
{
  assert(message->base.descriptor == &rpc__assistant_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__assistant_config__pack
                     (const Rpc__AssistantConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__assistant_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__assistant_config__pack_to_buffer
                     (const Rpc__AssistantConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__assistant_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__AssistantConfig *
       rpc__assistant_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__AssistantConfig *)
     protobuf_c_message_unpack (&rpc__assistant_config__descriptor,
                                allocator, len, data);
}
void   rpc__assistant_config__free_unpacked
                     (Rpc__AssistantConfig *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__assistant_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__kline__init
                     (Rpc__KLine         *message)
{
  static const Rpc__KLine init_value = RPC__KLINE__INIT;
  *message = init_value;
}
size_t rpc__kline__get_packed_size
                     (const Rpc__KLine *message)
{
  assert(message->base.descriptor == &rpc__kline__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__kline__pack
                     (const Rpc__KLine *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__kline__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__kline__pack_to_buffer
                     (const Rpc__KLine *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__kline__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__KLine *
       rpc__kline__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__KLine *)
     protobuf_c_message_unpack (&rpc__kline__descriptor,
                                allocator, len, data);
}
void   rpc__kline__free_unpacked
                     (Rpc__KLine *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__kline__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__security__init
                     (Rpc__Security         *message)
{
  static const Rpc__Security init_value = RPC__SECURITY__INIT;
  *message = init_value;
}
size_t rpc__security__get_packed_size
                     (const Rpc__Security *message)
{
  assert(message->base.descriptor == &rpc__security__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__security__pack
                     (const Rpc__Security *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__security__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__security__pack_to_buffer
                     (const Rpc__Security *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__security__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__Security *
       rpc__security__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__Security *)
     protobuf_c_message_unpack (&rpc__security__descriptor,
                                allocator, len, data);
}
void   rpc__security__free_unpacked
                     (Rpc__Security *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__security__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__securities__init
                     (Rpc__Securities         *message)
{
  static const Rpc__Securities init_value = RPC__SECURITIES__INIT;
  *message = init_value;
}
size_t rpc__securities__get_packed_size
                     (const Rpc__Securities *message)
{
  assert(message->base.descriptor == &rpc__securities__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__securities__pack
                     (const Rpc__Securities *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__securities__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__securities__pack_to_buffer
                     (const Rpc__Securities *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__securities__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__Securities *
       rpc__securities__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__Securities *)
     protobuf_c_message_unpack (&rpc__securities__descriptor,
                                allocator, len, data);
}
void   rpc__securities__free_unpacked
                     (Rpc__Securities *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__securities__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rpc__security_klines__init
                     (Rpc__SecurityKLines         *message)
{
  static const Rpc__SecurityKLines init_value = RPC__SECURITY_KLINES__INIT;
  *message = init_value;
}
size_t rpc__security_klines__get_packed_size
                     (const Rpc__SecurityKLines *message)
{
  assert(message->base.descriptor == &rpc__security_klines__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rpc__security_klines__pack
                     (const Rpc__SecurityKLines *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rpc__security_klines__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rpc__security_klines__pack_to_buffer
                     (const Rpc__SecurityKLines *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rpc__security_klines__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Rpc__SecurityKLines *
       rpc__security_klines__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Rpc__SecurityKLines *)
     protobuf_c_message_unpack (&rpc__security_klines__descriptor,
                                allocator, len, data);
}
void   rpc__security_klines__free_unpacked
                     (Rpc__SecurityKLines *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rpc__security_klines__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor rpc__request__field_descriptors[5] =
{
  {
    "uniqueid",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Rpc__Request, has_uniqueid),
    offsetof(Rpc__Request, uniqueid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "method",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__Request, method),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "protoname",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__Request, protoname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serialized_data",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Rpc__Request, serialized_data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "servertime",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Rpc__Request, has_servertime),
    offsetof(Rpc__Request, servertime),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__request__field_indices_by_name[] = {
  1,   /* field[1] = method */
  2,   /* field[2] = protoname */
  3,   /* field[3] = serialized_data */
  4,   /* field[4] = servertime */
  0,   /* field[0] = uniqueid */
};
static const ProtobufCIntRange rpc__request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor rpc__request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.Request",
  "Request",
  "Rpc__Request",
  "rpc",
  sizeof(Rpc__Request),
  5,
  rpc__request__field_descriptors,
  rpc__request__field_indices_by_name,
  1,  rpc__request__number_ranges,
  (ProtobufCMessageInit) rpc__request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__msg__field_descriptors[2] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__Msg, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "text",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__Msg, text),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__msg__field_indices_by_name[] = {
  0,   /* field[0] = code */
  1,   /* field[1] = text */
};
static const ProtobufCIntRange rpc__msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rpc__msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.Msg",
  "Msg",
  "Rpc__Msg",
  "rpc",
  sizeof(Rpc__Msg),
  2,
  rpc__msg__field_descriptors,
  rpc__msg__field_indices_by_name,
  1,  rpc__msg__number_ranges,
  (ProtobufCMessageInit) rpc__msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__number_msg__field_descriptors[1] =
{
  {
    "num",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Rpc__NumberMsg, has_num),
    offsetof(Rpc__NumberMsg, num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__number_msg__field_indices_by_name[] = {
  0,   /* field[0] = num */
};
static const ProtobufCIntRange rpc__number_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpc__number_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.NumberMsg",
  "NumberMsg",
  "Rpc__NumberMsg",
  "rpc",
  sizeof(Rpc__NumberMsg),
  1,
  rpc__number_msg__field_descriptors,
  rpc__number_msg__field_indices_by_name,
  1,  rpc__number_msg__number_ranges,
  (ProtobufCMessageInit) rpc__number_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__bytes_msg__field_descriptors[2] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__BytesMsg, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Rpc__BytesMsg, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__bytes_msg__field_indices_by_name[] = {
  0,   /* field[0] = code */
  1,   /* field[1] = data */
};
static const ProtobufCIntRange rpc__bytes_msg__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rpc__bytes_msg__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.BytesMsg",
  "BytesMsg",
  "Rpc__BytesMsg",
  "rpc",
  sizeof(Rpc__BytesMsg),
  2,
  rpc__bytes_msg__field_descriptors,
  rpc__bytes_msg__field_indices_by_name,
  1,  rpc__bytes_msg__number_ranges,
  (ProtobufCMessageInit) rpc__bytes_msg__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define rpc__ping__field_descriptors NULL
#define rpc__ping__field_indices_by_name NULL
#define rpc__ping__number_ranges NULL
const ProtobufCMessageDescriptor rpc__ping__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.Ping",
  "Ping",
  "Rpc__Ping",
  "rpc",
  sizeof(Rpc__Ping),
  0,
  rpc__ping__field_descriptors,
  rpc__ping__field_indices_by_name,
  0,  rpc__ping__number_ranges,
  (ProtobufCMessageInit) rpc__ping__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__login__field_descriptors[5] =
{
  {
    "accounttype",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Rpc__Login, has_accounttype),
    offsetof(Rpc__Login, accounttype),
    &rpc__account_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "openid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__Login, openid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "token",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__Login, token),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serverid",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Rpc__Login, has_serverid),
    offsetof(Rpc__Login, serverid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__Login, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__login__field_indices_by_name[] = {
  0,   /* field[0] = accounttype */
  4,   /* field[4] = name */
  1,   /* field[1] = openid */
  3,   /* field[3] = serverid */
  2,   /* field[2] = token */
};
static const ProtobufCIntRange rpc__login__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor rpc__login__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.Login",
  "Login",
  "Rpc__Login",
  "rpc",
  sizeof(Rpc__Login),
  5,
  rpc__login__field_descriptors,
  rpc__login__field_indices_by_name,
  1,  rpc__login__number_ranges,
  (ProtobufCMessageInit) rpc__login__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__third_party_authority__field_descriptors[5] =
{
  {
    "success",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Rpc__ThirdPartyAuthority, success),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "openid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__ThirdPartyAuthority, openid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sessionkey",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__ThirdPartyAuthority, sessionkey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__ThirdPartyAuthority, error),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__ThirdPartyAuthority, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__third_party_authority__field_indices_by_name[] = {
  4,   /* field[4] = code */
  3,   /* field[3] = error */
  1,   /* field[1] = openid */
  2,   /* field[2] = sessionkey */
  0,   /* field[0] = success */
};
static const ProtobufCIntRange rpc__third_party_authority__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor rpc__third_party_authority__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.ThirdPartyAuthority",
  "ThirdPartyAuthority",
  "Rpc__ThirdPartyAuthority",
  "rpc",
  sizeof(Rpc__ThirdPartyAuthority),
  5,
  rpc__third_party_authority__field_descriptors,
  rpc__third_party_authority__field_indices_by_name,
  1,  rpc__third_party_authority__number_ranges,
  (ProtobufCMessageInit) rpc__third_party_authority__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__broadcast_message__field_descriptors[3] =
{
  {
    "uids",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Rpc__BroadcastMessage, n_uids),
    offsetof(Rpc__BroadcastMessage, uids),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "protoname",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__BroadcastMessage, protoname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Rpc__BroadcastMessage, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__broadcast_message__field_indices_by_name[] = {
  2,   /* field[2] = data */
  1,   /* field[1] = protoname */
  0,   /* field[0] = uids */
};
static const ProtobufCIntRange rpc__broadcast_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor rpc__broadcast_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.BroadcastMessage",
  "BroadcastMessage",
  "Rpc__BroadcastMessage",
  "rpc",
  sizeof(Rpc__BroadcastMessage),
  3,
  rpc__broadcast_message__field_descriptors,
  rpc__broadcast_message__field_indices_by_name,
  1,  rpc__broadcast_message__number_ranges,
  (ProtobufCMessageInit) rpc__broadcast_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__deliver_message__field_descriptors[3] =
{
  {
    "serverid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__DeliverMessage, serverid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "protoname",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__DeliverMessage, protoname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Rpc__DeliverMessage, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__deliver_message__field_indices_by_name[] = {
  2,   /* field[2] = data */
  1,   /* field[1] = protoname */
  0,   /* field[0] = serverid */
};
static const ProtobufCIntRange rpc__deliver_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor rpc__deliver_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.DeliverMessage",
  "DeliverMessage",
  "Rpc__DeliverMessage",
  "rpc",
  sizeof(Rpc__DeliverMessage),
  3,
  rpc__deliver_message__field_descriptors,
  rpc__deliver_message__field_indices_by_name,
  1,  rpc__deliver_message__number_ranges,
  (ProtobufCMessageInit) rpc__deliver_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__server_info__field_descriptors[1] =
{
  {
    "serverid",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__ServerInfo, serverid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__server_info__field_indices_by_name[] = {
  0,   /* field[0] = serverid */
};
static const ProtobufCIntRange rpc__server_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpc__server_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.ServerInfo",
  "ServerInfo",
  "Rpc__ServerInfo",
  "rpc",
  sizeof(Rpc__ServerInfo),
  1,
  rpc__server_info__field_descriptors,
  rpc__server_info__field_indices_by_name,
  1,  rpc__server_info__number_ranges,
  (ProtobufCMessageInit) rpc__server_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const Rpc__AccountType rpc__player__accounttype__default_value = RPC__ACCOUNT_TYPE__Guest;
static const ProtobufCFieldDescriptor rpc__player__field_descriptors[4] =
{
  {
    "uid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__Player, uid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "openid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__Player, openid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__Player, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "accounttype",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Rpc__Player, has_accounttype),
    offsetof(Rpc__Player, accounttype),
    &rpc__account_type__descriptor,
    &rpc__player__accounttype__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__player__field_indices_by_name[] = {
  3,   /* field[3] = accounttype */
  2,   /* field[2] = name */
  1,   /* field[1] = openid */
  0,   /* field[0] = uid */
};
static const ProtobufCIntRange rpc__player__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor rpc__player__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.Player",
  "Player",
  "Rpc__Player",
  "rpc",
  sizeof(Rpc__Player),
  4,
  rpc__player__field_descriptors,
  rpc__player__field_indices_by_name,
  1,  rpc__player__number_ranges,
  (ProtobufCMessageInit) rpc__player__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue rpc__login_result__login_error__enum_values_by_number[4] =
{
  { "Auth_Error", "RPC__LOGIN_RESULT__LOGIN_ERROR__Auth_Error", 1 },
  { "Bind_Error", "RPC__LOGIN_RESULT__LOGIN_ERROR__Bind_Error", 2 },
  { "NoServer_Error", "RPC__LOGIN_RESULT__LOGIN_ERROR__NoServer_Error", 3 },
  { "OpenId_Error", "RPC__LOGIN_RESULT__LOGIN_ERROR__OpenId_Error", 4 },
};
static const ProtobufCIntRange rpc__login_result__login_error__value_ranges[] = {
{1, 0},{0, 4}
};
static const ProtobufCEnumValueIndex rpc__login_result__login_error__enum_values_by_name[4] =
{
  { "Auth_Error", 0 },
  { "Bind_Error", 1 },
  { "NoServer_Error", 2 },
  { "OpenId_Error", 3 },
};
const ProtobufCEnumDescriptor rpc__login_result__login_error__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "rpc.LoginResult.LoginError",
  "LoginError",
  "Rpc__LoginResult__LoginError",
  "rpc",
  4,
  rpc__login_result__login_error__enum_values_by_number,
  4,
  rpc__login_result__login_error__enum_values_by_name,
  1,
  rpc__login_result__login_error__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor rpc__login_result__field_descriptors[6] =
{
  {
    "succ",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Rpc__LoginResult, succ),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "player",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Rpc__LoginResult, player),
    &rpc__player__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "errorcode",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Rpc__LoginResult, has_errorcode),
    offsetof(Rpc__LoginResult, errorcode),
    &rpc__login_result__login_error__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serverids",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Rpc__LoginResult, n_serverids),
    offsetof(Rpc__LoginResult, serverids),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "magiccode",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__LoginResult, magiccode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "clearreceipt",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Rpc__LoginResult, has_clearreceipt),
    offsetof(Rpc__LoginResult, clearreceipt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__login_result__field_indices_by_name[] = {
  5,   /* field[5] = clearreceipt */
  2,   /* field[2] = errorcode */
  4,   /* field[4] = magiccode */
  1,   /* field[1] = player */
  3,   /* field[3] = serverids */
  0,   /* field[0] = succ */
};
static const ProtobufCIntRange rpc__login_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor rpc__login_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.LoginResult",
  "LoginResult",
  "Rpc__LoginResult",
  "rpc",
  sizeof(Rpc__LoginResult),
  6,
  rpc__login_result__field_descriptors,
  rpc__login_result__field_indices_by_name,
  1,  rpc__login_result__number_ranges,
  (ProtobufCMessageInit) rpc__login_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue rpc__error_code__error_type__enum_values_by_number[2] =
{
  { "RoomInvalid", "RPC__ERROR_CODE__ERROR_TYPE__RoomInvalid", 1 },
  { "ServerInvalid", "RPC__ERROR_CODE__ERROR_TYPE__ServerInvalid", 2 },
};
static const ProtobufCIntRange rpc__error_code__error_type__value_ranges[] = {
{1, 0},{0, 2}
};
static const ProtobufCEnumValueIndex rpc__error_code__error_type__enum_values_by_name[2] =
{
  { "RoomInvalid", 0 },
  { "ServerInvalid", 1 },
};
const ProtobufCEnumDescriptor rpc__error_code__error_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "rpc.ErrorCode.ErrorType",
  "ErrorType",
  "Rpc__ErrorCode__ErrorType",
  "rpc",
  2,
  rpc__error_code__error_type__enum_values_by_number,
  2,
  rpc__error_code__error_type__enum_values_by_name,
  1,
  rpc__error_code__error_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor rpc__error_code__field_descriptors[1] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Rpc__ErrorCode, code),
    &rpc__error_code__error_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__error_code__field_indices_by_name[] = {
  0,   /* field[0] = code */
};
static const ProtobufCIntRange rpc__error_code__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpc__error_code__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.ErrorCode",
  "ErrorCode",
  "Rpc__ErrorCode",
  "rpc",
  sizeof(Rpc__ErrorCode),
  1,
  rpc__error_code__field_descriptors,
  rpc__error_code__field_indices_by_name,
  1,  rpc__error_code__number_ranges,
  (ProtobufCMessageInit) rpc__error_code__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__key_value__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__KeyValue, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__KeyValue, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__key_value__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange rpc__key_value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rpc__key_value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.KeyValue",
  "KeyValue",
  "Rpc__KeyValue",
  "rpc",
  sizeof(Rpc__KeyValue),
  2,
  rpc__key_value__field_descriptors,
  rpc__key_value__field_indices_by_name,
  1,  rpc__key_value__number_ranges,
  (ProtobufCMessageInit) rpc__key_value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__configs__field_descriptors[1] =
{
  {
    "pairs",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Rpc__Configs, n_pairs),
    offsetof(Rpc__Configs, pairs),
    &rpc__key_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__configs__field_indices_by_name[] = {
  0,   /* field[0] = pairs */
};
static const ProtobufCIntRange rpc__configs__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpc__configs__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.Configs",
  "Configs",
  "Rpc__Configs",
  "rpc",
  sizeof(Rpc__Configs),
  1,
  rpc__configs__field_descriptors,
  rpc__configs__field_indices_by_name,
  1,  rpc__configs__number_ranges,
  (ProtobufCMessageInit) rpc__configs__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__assistant_config__field_descriptors[1] =
{
  {
    "json",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__AssistantConfig, json),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__assistant_config__field_indices_by_name[] = {
  0,   /* field[0] = json */
};
static const ProtobufCIntRange rpc__assistant_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpc__assistant_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.AssistantConfig",
  "AssistantConfig",
  "Rpc__AssistantConfig",
  "rpc",
  sizeof(Rpc__AssistantConfig),
  1,
  rpc__assistant_config__field_descriptors,
  rpc__assistant_config__field_indices_by_name,
  1,  rpc__assistant_config__number_ranges,
  (ProtobufCMessageInit) rpc__assistant_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__kline__field_descriptors[8] =
{
  {
    "date",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__KLine, date),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "open",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Rpc__KLine, open),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "high",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Rpc__KLine, high),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "low",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Rpc__KLine, low),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "close",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Rpc__KLine, close),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "volume",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Rpc__KLine, volume),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "factor",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Rpc__KLine, has_factor),
    offsetof(Rpc__KLine, factor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "amount",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Rpc__KLine, has_amount),
    offsetof(Rpc__KLine, amount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__kline__field_indices_by_name[] = {
  7,   /* field[7] = amount */
  4,   /* field[4] = close */
  0,   /* field[0] = date */
  6,   /* field[6] = factor */
  2,   /* field[2] = high */
  3,   /* field[3] = low */
  1,   /* field[1] = open */
  5,   /* field[5] = volume */
};
static const ProtobufCIntRange rpc__kline__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor rpc__kline__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.KLine",
  "KLine",
  "Rpc__KLine",
  "rpc",
  sizeof(Rpc__KLine),
  8,
  rpc__kline__field_descriptors,
  rpc__kline__field_indices_by_name,
  1,  rpc__kline__number_ranges,
  (ProtobufCMessageInit) rpc__kline__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__security__field_descriptors[6] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__Security, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "displayname",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__Security, displayname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "code",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__Security, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "begindate",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__Security, begindate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enddate",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__Security, enddate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__Security, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__security__field_indices_by_name[] = {
  3,   /* field[3] = begindate */
  2,   /* field[2] = code */
  1,   /* field[1] = displayname */
  4,   /* field[4] = enddate */
  0,   /* field[0] = name */
  5,   /* field[5] = type */
};
static const ProtobufCIntRange rpc__security__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor rpc__security__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.Security",
  "Security",
  "Rpc__Security",
  "rpc",
  sizeof(Rpc__Security),
  6,
  rpc__security__field_descriptors,
  rpc__security__field_indices_by_name,
  1,  rpc__security__number_ranges,
  (ProtobufCMessageInit) rpc__security__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__securities__field_descriptors[1] =
{
  {
    "securities",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Rpc__Securities, n_securities),
    offsetof(Rpc__Securities, securities),
    &rpc__security__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__securities__field_indices_by_name[] = {
  0,   /* field[0] = securities */
};
static const ProtobufCIntRange rpc__securities__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rpc__securities__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.Securities",
  "Securities",
  "Rpc__Securities",
  "rpc",
  sizeof(Rpc__Securities),
  1,
  rpc__securities__field_descriptors,
  rpc__securities__field_indices_by_name,
  1,  rpc__securities__number_ranges,
  (ProtobufCMessageInit) rpc__securities__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rpc__security_klines__field_descriptors[2] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Rpc__SecurityKLines, code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "klines",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Rpc__SecurityKLines, n_klines),
    offsetof(Rpc__SecurityKLines, klines),
    &rpc__kline__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rpc__security_klines__field_indices_by_name[] = {
  0,   /* field[0] = code */
  1,   /* field[1] = klines */
};
static const ProtobufCIntRange rpc__security_klines__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rpc__security_klines__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "rpc.SecurityKLines",
  "SecurityKLines",
  "Rpc__SecurityKLines",
  "rpc",
  sizeof(Rpc__SecurityKLines),
  2,
  rpc__security_klines__field_descriptors,
  rpc__security_klines__field_indices_by_name,
  1,  rpc__security_klines__number_ranges,
  (ProtobufCMessageInit) rpc__security_klines__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue rpc__account_type__enum_values_by_number[3] =
{
  { "Guest", "RPC__ACCOUNT_TYPE__Guest", 0 },
  { "WX", "RPC__ACCOUNT_TYPE__WX", 1 },
  { "Apple", "RPC__ACCOUNT_TYPE__Apple", 2 },
};
static const ProtobufCIntRange rpc__account_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex rpc__account_type__enum_values_by_name[3] =
{
  { "Apple", 2 },
  { "Guest", 0 },
  { "WX", 1 },
};
const ProtobufCEnumDescriptor rpc__account_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "rpc.AccountType",
  "AccountType",
  "Rpc__AccountType",
  "rpc",
  3,
  rpc__account_type__enum_values_by_number,
  3,
  rpc__account_type__enum_values_by_name,
  1,
  rpc__account_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
